version: "3.12"
services:
  db:
    image: postgres:16
    container_name: db_app
    env_file:
      - .env
    ports:
      - "5432:5432" 

  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - 15672:15672
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis_app
    command:
      --port 5379
    ports:
      - "5379:5379" 
    env_file:
      - .env 

  app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - 9999:8000
    depends_on:
      - db
      - rabbitmq
      - redis
    env_file:
      - .env

  celery:
    build: .
    container_name: celery_worker
    command: celery -A app.core.celery_utils.app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
      - redis
      - app
    env_file:
      - .env

  celery-beat:
    build: .
    container_name: celery_beat
    command: celery -A app.core.celery_utils.app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
      - redis
      - app
    env_file:
      - .env

  flower:
    build: .
    container_name: celery_flower
    command: celery -A app.core.celery_utils.app flower
    ports:
      - 5555:5555
    depends_on:
      - celery
      - app
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "80:80"
    depends_on:
      - app

